### ISSUE TITLE
Add .vscode config

### ISSUE THREAD

**Issue by wojtku** [zimekk/stack#3]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zimekk** [comment]
alexkrechik.cucumberautocomplete
peterjausovec.vscode-docker
dbaeumer.vscode-eslint
flowtype.flow-for-vscode
eamodio.gitlens
kumar-harsh.graphql-for-vscode
eg2.vscode-npm-script
esbenp.prettier-vscode

davidanson.vscode-markdownlint
christian-kohler.npm-intellisense
msjsdiag.debugger-for-chrome
vsmobile.vscode-react-native

**Comment by zimekk** [comment]
vscode-jest
